spring.application.name=app-admin
server.port=8082

# MySQL DataSource
spring.datasource.url=jdbc:mysql://db:3306/proyecto_integrador_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=admin_user
spring.datasource.password=admin_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logging (si es necesario)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.com.equipo=DEBUG

# H2 Console (ya no será necesario si migras completamente a MySQL, puedes comentarlo o eliminarlo)
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console